---
:mailboxes:
  -
    :email: "mail.room.sidekiq@gmail.com"
    :password: " "
    :name: "inbox"
    :delivery_method: sidekiq
    :delivery_options:
      :redis_url: redis://localhost:6379
      :worker: EmailReceiverWorker